project:
  type: website


website: 
  title: Quarto Website
  navbar:
    left:
      - index.qmd
      - callout-boxes.qmd
      - blog.qmd
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute: 
  freeze: auto
